# Update the image tag in the GitOps repository

name: Update GitOps Image Tag

on:
  workflow_call:
    secrets:
      GITOPS_PAT:
        description: "PAT with access to the GitOps repository"
        required: true
    inputs:
      gitops-repo:
        description: "Path to the GitOps repo"
        required: true
        type: string
      gitops-branch:
        description: "Branch to update"
        required: true
        type: string
      gitops-path:
        description: "Path to the deployment files"
        required: true
        type: string
      new-tag:
        description: "New image tag"
        required: true
        type: string

jobs:
  update-gitops-image-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Environment
        run: |
          echo "Checking if GITOPS_PAT exists (will not print value):"
          if [ -n "${{ secrets.GITOPS_PAT }}" ]; then
            echo "✓ GITOPS_PAT is set"
          else
            echo "✗ GITOPS_PAT is not set"
            echo "::error::The GITOPS_PAT secret is required but not available. Make sure it's defined in the calling repository and passed with 'secrets: inherit'"
            exit 1
          fi
          echo "GitOps Repo: ${{ inputs.gitops-repo }}"
          echo "GitOps Branch: ${{ inputs.gitops-branch }}"
          echo "GitOps Path: ${{ inputs.gitops-path }}"

      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.gitops-repo }}
          ref: ${{ inputs.gitops-branch }}
          # GITOPS_PAT must be defined in the calling repo's secrets
          # This token needs repo scope access to the private gitops repository
          token: ${{ secrets.GITOPS_PAT }}

      - name: Update Kustomization Image Tag
        working-directory: ${{ inputs.gitops-path }}
        run: |
          kustomize edit set image "APP_IMAGE=*:${{ inputs.new-tag }}"

      - name: Commit and Push Changes
        run: |
          git config user.email "ggsrc-bot@users.noreply.github.com"
          git config user.name "ggsrc-bot"
          git add .
          git commit -m "ci(deploy): update ${{ inputs.gitops-path }} image tag to ${{ inputs.new-tag }}"
          git push origin ${{ inputs.gitops-branch }}
